Better global support
replit/prybar pull request #59
Opened 2020-09-08 06:34 UTC by amasad

In the current implementation, `instanceof` fails because we get classes like `Array` and `Object` from a different realm. 

With this, we only copy things that are missing from the context (and the console).

2020-09-10 22:29 UTC, masad-frost requested changes

2020-09-10 22:29 UTC, masad-frost commented on languages/nodejs/repl.js
> +  context.global = context;
Ideally we make this non-writable.

2020-09-10 22:29 UTC, masad-frost commented on languages/nodejs/repl.js
> +  new Set(vm.runInNewContext('Object.getOwnPropertyNames(globalThis)'));
:nit:
```suggestion
  const globalBuiltins =
    new Set(vm.runInNewContext('Object.getOwnPropertyNames(globalThis)'));
```
or
```suggestion
  const globalBuiltins = new Set(vm.runInNewContext('Object.getOwnPropertyNames(globalThis)'));
```

2020-09-10 22:29 UTC, masad-frost commented on languages/nodejs/repl.js
> +  new Set(vm.runInNewContext('Object.getOwnPropertyNames(globalThis)'));
Actually let's run this in the our context, seems more sane
```suggestion
  const globalBuiltins = vm.runInContext('Object.getOwnPropertyNames(global)', context);
```

2020-09-10 22:29 UTC, masad-frost commented on languages/nodejs/repl.js
> +  context.global = context;
It makes sense to set this before the loop.
Also on line 144 and 145 we set the `context.root` and `context.GLOBAL` to equal this script's global, we should remove them.

Node 12 also adds `globalThis` which [seems to be the future of all global objects ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis)

Here's something i wrote before, it includes deprecation notices.

```suggestion
const util = require('util');

// VM context doesn't have a built-in "global", so we
// have to tell it to point to itself
Object.defineProperties(context, {
  global: {
    ...Object.getOwnPropertyDescriptor(global, 'global'),
    value: context,
  },
  globalThis: {
    ...Object.getOwnPropertyDescriptor(global, 'globalThis'),
    value: context,
  },
  GLOBAL: {
    ...Object.getOwnPropertyDescriptor(global, 'GLOBAL'),
    get: util.deprecate(() => context, `'GLOBAL' is deprecated, use 'global'`, 'DEP0016'),
    set: util.deprecate(
      (value) => {
        Object.defineProperty(context, 'GLOBAL', {
          configurable: true,
          writable: true,
          enumerable: true,
          value: value,
        });
      },
      `'GLOBAL' is deprecated, use 'global'`,
      'DEP0016',
    ),
  },
  root: {
    ...Object.getOwnPropertyDescriptor(global, 'root'),
    get: util.deprecate(() => context, `'root' is deprecated, use 'global'`, 'DEP0016'),
    set: util.deprecate(
      (value) => {
        Object.defineProperty(context, 'root', {
          configurable: true,
          writable: true,
          enumerable: true,
          value: value,
        });
      },
      `'root' is deprecated, use 'global'`,
      'DEP0016',
    ),
  },
});
```

2020-09-10 22:29 UTC, masad-frost commented on languages/nodejs/repl.js
> +  context.global = context;
I also think it would be better to do this before the loop for defining other properties

2020-09-10 22:29 UTC, masad-frost commented on test_files/global_bug.js
> +console.log([] instanceof global.Array);
Lovely test! Can we also add a test for things that are completely missing from the context's global. Here's a list, make your pick.

```
process
URL
URLSearchParams
clearImmediate
clearInterval
clearTimeout
setImmediate
setInterval
setTimeout
Buffer
```

2020-09-10 22:29 UTC, masad-frost commented on test_files/global_bug.js
> +console.log([] instanceof global.Array);
```suggestion
console.log([] instanceof global.Array);
console.log(Boolean(process));
```

2020-09-10 22:29 UTC, masad-frost commented on tests/nodejs/global_bug.exp
> +\u001b\[33mtrue\u001b\[39m\r
To go with the above suggestion in test_files
```suggestion
\u001b\[33mtrue\u001b\[39m\r
\u001b\[33mtrue\u001b\[39m\r
```

2020-09-11 17:26 UTC, amasad commented
- Removed globals
- Added more tests
- Fixed nits

2020-09-12 02:18 UTC, merged